apiVersion: apps/v1
kind: Deployment
metadata:
  name: lez09-isolation-deployment
  namespace: lez09-sms
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: lez09-sms-pod
  template:                       # Specifica template del POD
    metadata:
      labels:
        app: lez09-sms-pod  
    spec:
      containers:
        - name: lez09-sms-pod
          image: archety/student-api-in-memory:latest
          
          imagePullPolicy: Always

          env:
            - name: APP_NAME
              value: "minikube-gio-test"
            - name: APP_PROFILE
              value: "production"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
            
