apiVersion: v1
kind: Pod

metadata:
  name: laboratorio-web
  namespace: lab-web

spec:
  containers:
    - name: nginx-ws
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
          protocol: TCP