apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: school-ingress
  namespace: school-ns
spec:
  ingressClassName: nginx
  rules:
    - host: school.local
      http:
        paths:
          - path: /api/books
            pathType: Prefix  # Qualsiasi segmento dopo la /api/books
            backend:
              service:
                name: books-service
                port:
                  number: 80
          
          - path: /api/students
            pathType: Prefix  # Qualsiasi segmento dopo la /api/books
            backend:
              service:
                name: students-service
                port:
                  number: 80