apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: school-ns
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dG9vcg==     ## toor
  MYSQL_USER: c3R1ZGVudHVzZXI=      ## Utente usato dalla REST API
  MYSQL_PASSWORD: c3R1ZGVudHBhc3M=