apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-volume-claim
  namespace: school-ns
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
