apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-volume
  namespace: school-ns
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql
