apiVersion: v1
kind: Service
metadata:
  name: rest-service
  namespace: school-ns
spec:
  selector:
    app: sms-rest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30008
  type: NodePort