apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap.dev
  namespace: universita-ns
data:
  APP_MESSAGE: "Ciao sono Giovanni Pace"
  APP_MODE: "dev"
  APP_DEBUG: "true"
  APP_DB_URL: "8.5.2.4"