apiVersion: v1
kind: Pod
metadata:
  name: turing-test-pod-tre
  namespace: turing-ns
spec:
  containers:
    - name: nginx-ws-uno
      image: nginx:latest
      ports:
        - containerPort: 83
    - name: nginx-ws-due
      image: nginx:1.31.1
      ports:
        - containerPort: 81
