apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: ferramenta-ns
type: Opaque
data:
  username: QUIxMjM0NQ==        # AB12345 in Base64
  password: ODg4ZmRjQCE1MQ==    # 888fdc@!51 in Base64